services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: peoplemap
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-db-net
    ports:
      - "5432:5432"
  backend:
    build: backend
    ports:
      - "8080:8080"
    networks:
      - backend-db-net
    depends_on:
      db:
        condition: service_started
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
        restart: true
volumes:
  db_data:
networks:
  backend-db-net:
