services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: peoplemap
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-db-net
    ports:
      - "5432:5432"
volumes:
  db_data:
networks:
  backend-db-net:
